---
title: "Figure3"
author: "Devi Veytia"
date: "2023-12-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Figure description/overview

This figure shows the methods development stages across the different OROs using a barplot (fill, ORO type, x axis, method type)


# Set up

```{r load libraries}
library(dplyr)
library(dbplyr)
library(R.utils)
library(RSQLite)
library(ggplot2)
```


```{r Get the latest version of sqlite database and connect}

sqliteDir <- here::here("data/sqlite-databases")
sqliteFiles <- dir(sqliteDir)
sqliteVersions <- as.numeric(gsub(".sqlite","",substring(sqliteFiles, regexpr("_v", sqliteFiles) + 2)))
latestVersion <- sqliteFiles[which.max(sqliteVersions)]
dbcon <- RSQLite::dbConnect(RSQLite::SQLite(), file.path(sqliteDir, latestVersion), create=FALSE)
```


```{r import common aesthetics}
factor_aes <- readxl::read_excel(here::here("R/factor_aesthetics.xlsx"))

```


```{r import the summary of model scores}
modelScoresFileName <- dir(here::here("data"))
modelScoresFileName <- modelScoresFileName[grep("model_scores", modelScoresFileName)]

if(length(modelScoresFileName) > 1){
  versionScores <- as.Date(gsub(".csv","", gsub("summary_model_scores_","",modelScoresFileName)))
  modelScoresFileName <- modelScoresFileName[which.max(versionScores)]
}

modelScores <- readr::read_csv(here::here("data", paste(modelScoresFileName)))

```

# Format data for figure

```{r Calculate sums for different methods by ORO type}
predRel <- tbl(dbcon, "pred_relevance") %>%
  filter(0.5 <= relevance_mean) %>%
  select(analysis_id)
predType <- tbl(dbcon, "pred_oro_type_long") %>%
  filter(0.5 <= mean) %>%
  select(analysis_id, oro_branch, oro_type)
predMethod <- tbl(dbcon, "pred_method_type") %>%
  select(analysis_id, 
         `method_type.Mathematical_predictionsimulation - mean_prediction`,
         `method_type.Social_primary - mean_prediction`,
         `method_type.Empirical - mean_prediction`)

## Calculations for plotting

# Join datasets for relevance, orotype and method predictions
typeMethodDf <- predRel %>%
  inner_join(predType, by ="analysis_id") %>%
  inner_join(predMethod, by = "analysis_id") %>%
  # For each ORO type, sum the number of predictions for each method type
  group_by(oro_branch, oro_type) %>%
  summarise(
    Mathematical_predictionsimulation = sum(0.5 <= `method_type.Mathematical_predictionsimulation - mean_prediction`),
    Social_primary = sum(0.5 <= `method_type.Social_primary - mean_prediction`),
    Empirical = sum(0.5 <= `method_type.Empirical - mean_prediction`)
  ) %>%
  collect()

# Melt dataframe
typeMethodDf <- reshape2::melt(typeMethodDf, 
                               id.vars = c("oro_branch","oro_type"),
                               variable.name = "method_type", 
                               value.name = "method_sum")

# Calculate totals for each oro to plot sums as a proportion
oroTotals <- predRel %>%
  inner_join(predType, by ="analysis_id") %>%
  inner_join(predMethod, by = "analysis_id") %>%
  # For each ORO type, sum the number of predictions for each method type
  group_by(oro_type) %>%
  summarise(oroTotal = n()) %>%
  collect()
typeMethodDf <- merge(typeMethodDf, oroTotals, by = "oro_type")

# Use oroTotals to calculate the number of "other" methods
otherMethods <- typeMethodDf %>%
  group_by(oro_type, oro_branch, oroTotal) %>%
  summarise(
    sum_allMethods = sum(method_sum) 
  ) %>%
  mutate(method_sum = oroTotal-sum_allMethods,
         method_type = "Other") 
otherMethods <- otherMethods[,colnames(typeMethodDf)]
typeMethodDf <- rbind(typeMethodDf, otherMethods)

# Calculate method sums as a percent of total
typeMethodDf$method_percent <- round(typeMethodDf$method_sum/typeMethodDf$oroTotal*100)



## Format aesthetics for plotting

# Factor oro_type columns for both methods and totals dataframes 
typeAES <- factor_aes[which(factor_aes$variable == "oro_type"),]
typeAES <- typeAES[order(typeAES$order),]

typeMethodDf <- typeMethodDf %>%
  merge(typeAES %>%
          rename(oro_type=level) %>%
          select(oro_type, order), by="oro_type") %>%
  mutate(oro_type = factor(oro_type, levels = typeAES$level, labels = typeAES$label),
         order = factor(order, levels = typeAES$order))

oroTotals$oro_type <- factor(
  oroTotals$oro_type,
  levels = typeAES$level, labels = typeAES$label
)
oroTotals <- typeAES %>%
  rename(oro_type = label) %>%
  select(oro_type, order) %>%
  merge(oroTotals) %>%
  mutate(order = factor(order, levels = typeAES$order[order(typeAES$order)]))


# Factor Method type
methodAES <- factor_aes[which(factor_aes$variable == "method_type"),]
methodAES <- methodAES[order(methodAES$order,decreasing = FALSE),]

typeMethodDf$method_type <- factor(
  typeMethodDf$method_type, 
  levels = methodAES$level, labels = methodAES$label
)
# set colours according to method_type
methodAES$method_type <- methodAES$label
typeMethodDf <- merge(typeMethodDf, #  %>% select(-c("colour"))
                      methodAES[,c("method_type","colour")],
                      by = "method_type")

# Summarise dataset
summary(typeMethodDf)




# Also calculate the overall % empirical (i.e. empirical + social primary)
percentEmpirical <- typeMethodDf %>%
  filter(grepl("Empirical", method_type)) %>%
  group_by(oro_type, order) %>%
  summarise(percentEmpirical = sum(method_percent))
  
  

```

```{r write table to csv}
write.csv(typeMethodDf %>% select(oro_type, method_type, method_sum, oroTotal, method_percent) %>% arrange(oro_type, method_type),here::here("outputs/methodTypeByOROTypeSummaryTable.csv"))

```

# Write figure

```{r plot total numbers of predictions per method, eval=FALSE}
fig3_ggp <- ggplot(typeMethodDf, aes(y=order, x=method_sum, fill = method_type))+
  # plot bars number of model predictions
  geom_col(position = "stack")+
  
  # Format scales
  scale_fill_brewer(name = "Method type",type = "qual", palette = "Dark2")+
  scale_y_discrete(limits = rev(levels(typeMethodDf$order)), 
                    labels = rev(levels(typeMethodDf$oro_type)))+
  
  labs(x="N articles")+
  theme(
    panel.background = element_rect(fill="white",colour = "black"),
    panel.grid.major = element_line(colour = "grey"),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank()
  )

fig3_ggp

```


```{r plot as a proportion of total studies}
# Join legend labels with model scores to add F1 statistic to label
methodTypeScores <- modelScores%>% 
  filter(model == "method_type_simplified") %>% 
  select(`label name`, `F1 - label`) %>%
  filter(!is.na(`F1 - label`)) %>%
  mutate(`label name` = recode(`label name`,
                          `method_type.Mathematical_predictionsimulation` = "Prediction/simulation",
                          `method_type.Social_primary` = "Empirical - social primary",
                          `method_type.Empirical` = "Empirical - other"
                        )) %>%
  rename(label = `label name`, F1 = `F1 - label`)


legendLabels <- merge(factor_aes[which(factor_aes$variable == "method_type"),],
                      methodTypeScores,
                      by = "label", all.x = TRUE)%>%
  mutate(legendLabelF1 = paste0(label,", F1 = ", signif(F1, 2)))
legendLabels$legendLabelF1[which(legendLabels$label == "Other")] <- "Other"



## Plot

fig3_ggp <- ggplot(typeMethodDf, aes(x=order, y=method_percent))+
  # plot bars number of model predictions
  geom_col(position = "stack", aes(fill = method_type))+
  geom_text(data = oroTotals, aes(x=order,label = oroTotal), y=105, size=3, col="black", inherit.aes = FALSE)+ 
  geom_text(data = percentEmpirical, aes(x=order,label = paste(percentEmpirical,"%")), 
            y=115, size=3, col="darkgreen", inherit.aes = FALSE)+ 
  
  # Add vertical lines to separate branches
  geom_vline(xintercept = c(3.5,5.5))+
  
  # Format scales
  scale_fill_manual(name = "Method type",
                    values = as.vector(methodAES$colour), 
                    labels = legendLabels$legendLabelF1[order(legendLabels$order)],## adds F1 statistic to label
                    guide = guide_legend(nrow=2))+
  scale_x_discrete(limits = levels(typeMethodDf$order), 
                    labels = levels(typeMethodDf$oro_type))+
  scale_y_continuous(limits = c(0,115), breaks = seq(0,100, by = 25))+
  
  labs(y="Percent contribution")+
  theme(
    panel.background = element_rect(fill="white",colour = "black"),
    panel.grid.major = element_blank(),
    axis.text.x = element_text(angle=45, hjust=1,size=10),
    axis.title.x = element_blank(),
    plot.margin = unit(c(0.15,0.15,0.5,1),'cm'),
    legend.position = "bottom"
  )

fig3_ggp
```

```{r write figure}

ggsave(filename = here::here("figures/main/methodsBarPlot.pdf"),plot = fig3_ggp,width = 7,height=5, units='in')
```


# Supplementary figure decomposing methods contribution by time

```{r Calculate percent contribution of different methods by year}

predRel <- tbl(dbcon, "pred_relevance") %>%
  filter(0.5 <= relevance_mean) %>%
  select(analysis_id)
predType <- tbl(dbcon, "pred_oro_type_long") %>%
  filter(0.5 <= mean) %>%
  select(analysis_id, oro_branch, oro_type)
predMethod <- tbl(dbcon, "pred_method_type") %>%
  select(analysis_id, 
         `method_type.Mathematical_predictionsimulation - mean_prediction`,
         `method_type.Social_primary - mean_prediction`,
         `method_type.Empirical - mean_prediction`)
uniquerefs <- tbl(dbcon, "uniquerefs")

## Calculations for plotting

# Join datasets for relevance, orotype and method predictions
typeMethodDfYear <- predRel %>%
  inner_join(predType, by ="analysis_id") %>%
  inner_join(predMethod, by = "analysis_id") %>%
  inner_join(uniquerefs %>% select(analysis_id, year) %>% filter(!is.na(year)), by = "analysis_id") %>%
  # For each ORO type and year, sum the number of predictions for each method type
  group_by(oro_branch, oro_type, year) %>%
  summarise(
    Mathematical_predictionsimulation = sum(0.5 <= `method_type.Mathematical_predictionsimulation - mean_prediction`),
    Social_primary = sum(0.5 <= `method_type.Social_primary - mean_prediction`),
    Empirical = sum(0.5 <= `method_type.Empirical - mean_prediction`),
    oro_total = n()
  ) %>%
  collect()

# Melt dataframe
typeMethodDfYear <- reshape2::melt(typeMethodDfYear, 
                               id.vars = c("oro_branch","oro_type","year", "oro_total"),
                               variable.name = "method_type", 
                               value.name = "method_sum")

# Calculate method sums as a percent of total
typeMethodDfYear$method_percent <- round(typeMethodDfYear$method_sum/typeMethodDfYear$oro_total*100)



## Factor aesthetics
# Factor oro_type columns for both methods and totals dataframes 
typeAES <- factor_aes[which(factor_aes$variable == "oro_type"),]
typeAES <- typeAES[order(typeAES$order),]

methodAES <- factor_aes[which(factor_aes$variable == "method_type"),]
methodAES <- methodAES[order(methodAES$order,decreasing = FALSE),]

typeMethodDfYear <- typeMethodDfYear %>%
  # merge(typeAES %>%
  #         rename(oro_type=level) %>%
  #         select(oro_type, order), by="oro_type") %>%
  mutate(oro_type = factor(oro_type, levels = typeAES$level, labels = typeAES$label),
         method_type = factor(method_type, 
                              levels = methodAES$level[-grep("Other", methodAES$level)],
                              labels = methodAES$label[-grep("Other", methodAES$label)]),
         year = as.Date(paste0(year,"-01-01")))



```


```{r plot supplemental figure of method types by year}
#require(ggnewscale)

SFig_methodYear <- ggplot(data=typeMethodDfYear %>% filter(as.Date("1980-01-01") <= year) %>%
                            mutate(oro_total_year = nlevels(typeMethodDfYear$method_type)+1))+
  facet_grid(rows=vars(oro_type),labeller = label_wrap_gen(width=15))+
  geom_tile(aes(x=year, y=as.factor(as.numeric(method_type)), fill=method_percent))+
  scale_fill_distiller(name="% contribution", palette = "Blues", direction = 1)+
  #scale_fill_viridis_c(name="% contribution", option = "viridis")+
  # new_scale_fill()+
  # geom_tile(aes(x=year, fill = oro_total, y=oro_total_year))+
  # scale_fill_viridis_c(name="N articles", option = "magma")+
  geom_hline(yintercept=nlevels(typeMethodDfYear$method_type)+0.5)+
  geom_text(aes(x=year, label=formatC(oro_total, format = "d", big.mark=",")),
            y=nlevels(typeMethodDfYear$method_type)+1,
            size = 2, angle=90, hjust=0)+
  
  scale_y_discrete(name = "Method type",
                   limits = factor(seq(1, nlevels(typeMethodDfYear$method_type)+2)),
                   labels = c(levels(typeMethodDfYear$method_type), "N articles",""))+

  scale_x_date(name = "Year")+
  
  theme_bw()+
  theme(
    panel.grid.major = element_blank(),
    legend.position = "right",
    axis.ticks.y = element_blank(),
    strip.text = element_text(size=6)
  )
  
SFig_methodYear


```

```{r save supplemental method type hovmoller plot}
ggsave(here::here("figures/supplemental/methodTypeHovmoller.pdf"),
       plot=SFig_methodYear,
       width=7, height=6, units="in")
```


# Alternative main figure combining Hovmoller plot with proportions displayed as doughnut plot

```{r plot supplemental figure of method types by year with doughnuts showing proportions}

## Panel a of the plot showing the % contributions through time

SFig_methodYear_A <- ggplot(data=typeMethodDfYear %>% filter(as.Date("1980-01-01") <= year) %>%
                            mutate(oro_total_year = nlevels(typeMethodDfYear$method_type)+1))+
  facet_grid(rows=vars(oro_type),labeller = label_wrap_gen(width=15))+
  geom_tile(aes(x=year, y=as.factor(as.numeric(method_type)), fill=method_percent))+
  scale_fill_distiller(name="% contribution", palette = "Blues", direction = 1)+
  # new_scale_fill()+
  # geom_tile(aes(x=year, fill = oro_total, y=oro_total_year))+
  # scale_fill_viridis_c(name="N articles", option = "magma")+
  geom_hline(yintercept=nlevels(typeMethodDfYear$method_type)+0.5)+
  geom_text(aes(x=year, label=formatC(oro_total, format = "d", big.mark=",")),
            y=nlevels(typeMethodDfYear$method_type)+1,
            size = 2, angle=90, hjust=0)+
  
  scale_y_discrete(name = "Method type",
                   limits = factor(seq(1, nlevels(typeMethodDfYear$method_type)+2)),
                   labels = c(levels(typeMethodDfYear$method_type), "N articles",""))+

  scale_x_date(name = "Year")+
  
  theme_bw()+
  theme(
    panel.grid.major = element_blank(),
    legend.position = "bottom",
    axis.ticks.y = element_blank(),
    strip.text = element_text(size=6)
  )
  
SFig_methodYear_A


## Panel B showing doughnut plots of overall proportions
SFig_methodYear_B <- typeMethodDf %>%
  arrange(oro_type, method_type) %>%
  group_by(oro_type) %>%
  mutate(ymax = cumsum(method_percent)) %>% 
  mutate(ymax = ifelse(method_type == "Other", 100, ymax),
         ymin = lag(ymax, default = 0)) %>% 
  ggplot()+
  facet_grid(rows = vars(oro_type))+
  geom_rect(aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = method_type))+
  # geom_text(data = oroTotals, aes(x=3,label = oroTotal), y=0, size=2, col="black", inherit.aes = FALSE,vjust = 1, hjust=0.5)+ 
  xlim(c(2,4))+
  coord_polar(theta = "y")+
  
  # Format scales
  scale_fill_manual(name = "Method type",
                    values = as.vector(methodAES$colour))+
  # scale_x_discrete(limits = levels(typeMethodDf$order), 
  #                   labels = levels(typeMethodDf$oro_type))+
  # ylim(c(0,105))+
  # guides(fill=guide_legend(ncol=2))+
  
  # labs(y="Percent contribution")+
  theme(
    panel.background = element_rect(fill="white",colour = "white"),
    panel.grid.major = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    strip.background = element_blank(),
    strip.text = element_blank(),
    legend.position = "right"
  )

SFig_methodYear_B


```


```{r save supplemental method type hovmoller plot}
require(cowplot)

pdf(file = here::here("figures/main/methodsHovmollerDoughnut.pdf"),
    width = 9, height = 7)
plot_grid(SFig_methodYear_A,
          SFig_methodYear_B+theme(plot.margin = unit(c(0,0,2.75,0), "cm")), 
          rel_widths = c(1,0.5), rel_heights = c(1,0.2), ncol=2) #labels = list("a.","b."), label_size = 17
while (!is.null(dev.list())) dev.off()
```




