---
title: "mCDR research in France March 2024"
author: "Devi Veytia"
date: "2024-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up

```{r load libraries}
library(dplyr)
library(dbplyr)
library(R.utils)
library(RSQLite)
library(ggplot2)
```


```{r Get the latest version of sqlite database and connect}

sqliteDir <- here::here("data/sqlite-databases")
sqliteFiles <- dir(sqliteDir)
sqliteVersions <- as.numeric(gsub(".sqlite","",substring(sqliteFiles, regexpr("_v", sqliteFiles) + 2)))
latestVersion <- sqliteFiles[which.max(sqliteVersions)]

```


```{r import common aesthetics}
factor_aes <- readxl::read_excel(here::here("R/factor_aesthetics.xlsx"))
```

```{r functions to format}
source(here::here("R", "functions_to_format.R")) 
source(here::here("R", "utils.R")) 
source(here::here("R", "clean_string.R")) 
source(here::here("R", "bool_detect.R")) 


```

```{r load data formattted below}
load(here::here("data/mCDR_data_March2024_beforeKeyword.RData"))
```

```{r Retrieve and format data - skip and load from prev chunk, eval = FALSE}
## Assemble necessary tables
dbcon <- RSQLite::dbConnect(RSQLite::SQLite(), file.path(sqliteDir, latestVersion), create=FALSE)

# ML model predictions
predRel <- tbl(dbcon, "pred_relevance") %>%
  select(analysis_id, relevance_mean) %>%
  filter(0.5 <= relevance_mean)
pred_mCDR <- tbl(dbcon, "pred_oro_type_long") %>%
  filter(oro_type == "CO2 removal or storage" & 0.5 <= mean) %>%
  select(analysis_id)
pred_blue_carbon <- tbl(dbcon, "pred_blue_carbon") %>%
  select(analysis_id, "0 - relevance - mean_prediction") %>%
  rename(blue_carbon = `0 - relevance - mean_prediction`)
pred_empirical <- tbl(dbcon, "pred_method_type") %>%
  select(analysis_id, "method_type.Empirical - mean_prediction") %>%
  rename(empirical = `method_type.Empirical - mean_prediction`)
# database metadata
uniquerefs <- tbl(dbcon, "allrefs") %>%
  select(analysis_id, affiliation, year, title, abstract, keywords)




## Subset to only mCDR options
# and add indicator column for blue carbon and method type
# Also add in metadata on year, first author affiliation, and title+abstract text for keyword searches
mCDR_df <- predRel %>%
  inner_join(pred_mCDR, by = "analysis_id")%>%
  inner_join(uniquerefs, by = "analysis_id") %>%
  left_join(pred_blue_carbon, by = "analysis_id")%>%
  left_join(pred_empirical, by = "analysis_id") %>%
  collect()

## disconnect
DBI::dbDisconnect(dbcon)



# Extract country of 1st auth affiliation
# list of countries for extracting country of 1st auth affiliation
countries_ls <- read.csv(file = here::here("data", "external", "list_of_countries", "sql-pays.csv"), sep = ";") |>  # Countries names
    dplyr::mutate(country = countrycode::countrycode(sourcevar   = name_en,
                                        origin      = "country.name",
                                        destination = "country.name"),
                  iso_code = countrycode::countrycode(sourcevar   = country,
                                         origin      = "country.name",
                                         destination = "iso3c"))
data_1stA_country <- extract_1stA_affiliation(data = mCDR_df[,c("analysis_id", "affiliation")], countries_ls = countries_ls) 

mCDR_df <- mCDR_df %>%
  left_join(data_1stA_country$oroAff_1stA[,c("analysis_id","country_aff")], by = "analysis_id")

## Identify the top 10 countries
country_1stA_tab <- with(mCDR_df, table(country_aff))
country_1stA_tab <- country_1stA_tab[order(country_1stA_tab, decreasing = TRUE)]
top10 <- head(country_1stA_tab,10)
# if france isn't in the top 10, add in
if(sum(grepl("france", names(top10), ignore.case = TRUE)) == 0){
  top10 <- c(top10, country_1stA_tab[grep("france", names(country_1stA_tab), ignore.case = TRUE)])
}
# subset data to these countries
mCDR_df_top10 <- mCDR_df %>%
  filter(country_aff %in% names(top10))



## Clean workspace
rm(mCDR_df, countries_ls, data_1stA_country)



# Save
# save(mCDR_df_top10, file = here::here("data/mCDR_data_March2024_beforeKeyword.RData"))

```




# Timeline of publications in top 10 countries

````{r plot a cumulative time series of the top 10 countries}
load(here::here("data/mCDR_data_March2024_beforeKeyword.RData"))
library(gcookbook)

top10 <- with(mCDR_df_top10, table(country_aff))
top10 <- top10[order(top10, decreasing = TRUE)]
myPal <- viridis::mako(length(top10))
myPal[which(names(top10) == "France")] <- "orange"
names(myPal) <- names(top10)

timeseries_ggp <- mCDR_df_top10 %>%
  filter(!is.na(year)) %>%
  mutate(country_aff = factor(country_aff, levels = names(top10))) %>%
  group_by(year, country_aff) %>%
  summarise(n_articles = n_distinct(analysis_id)) %>%
  mutate(year_date = as.Date(paste0(year,"-01-01"))) %>% 
  filter(year_date < as.Date("2023-01-01")) %>%
  
  ggplot(aes(x = year_date, y = n_articles, fill = country_aff)) +
  geom_area(colour = "black", size = .2, alpha = .4) +
  #scale_fill_brewer(palette = "Blues")+
  scale_fill_manual(values = myPal) +
  scale_x_date()+
  labs(x="Year", y ="N articles", fill = "Country")+
  theme_bw()+
  theme(
    axis.text.x = element_text(size=13),
    axis.text.y = element_text(size=13),
    legend.text = element_text(size=13),
    axis.title.x = element_text(size=15),
    axis.title.y = element_text(size=15),
    legend.title = element_text(size=15)
  )


ggsave(timeseries_ggp,
       filename = here::here("figures/mCDR_research_in_france_March2024/timeseries.png"),
       width = 7, height = 5, dpi = 600)

```


# Map geoparsed data in top 10 countries for only empirical studies

```{r format geoparsed data}
## Assemble data
# relevant articles
load(here::here("data/mCDR_data_March2024_beforeKeyword.RData"))

# geoparsing tables
dbcon <- RSQLite::dbConnect(RSQLite::SQLite(), file.path(sqliteDir, latestVersion), create=FALSE)
grid_df <- tbl(dbcon, "grid_df_res2.5") %>% collect()
shp_df_matches <- tbl(dbcon, "geoparsed-text_shp_df_matches") %>% collect()
DBI::dbDisconnect(dbcon)

# merge the two
mCDR_df_top10_geo <- mCDR_df_top10 %>%
  filter(0.5 <= empirical) %>%
  inner_join(shp_df_matches, by = "analysis_id")

# clean workspace
rm(shp_df_matches)

# calculate the weighted sum
weightedSum <- mCDR_df_top10_geo %>%
  group_by(grid_df_id) %>%
  summarise(n_articles = sum(cell_weight))

# merge in with information on grid cell location
grid_df_mCDR <- grid_df %>%
  left_join(weightedSum, by = "grid_df_id")



## Set new grid dataframe with new info
grid_df2 <- grid_df


# ## Within the EEZ----------------------------
# require(raster)
# eez_rast <- raster::raster(here::here("data", "external", "eez_rast", "rast_iso_eez.asc"))
# eez_rast[eez_rast==0] <- NA
# 
# # extract eez value at grid cell points
# grid_df2$eez_vals <- raster::extract(eez_rast, grid_df[,c("LON","LAT")])
# 
# # check
# grid_df2 %>%
#   filter(!is.na(eez_vals)) %>%
#   ggplot(aes(LON, LAT, fill=eez_vals))+
#   geom_tile()



## Remove land cells > 200 km inland ---------------------------
# Used this as inspo: https://dominicroye.github.io/en/2019/calculating-the-distance-to-the-sea-in-r/
require(sf)

coast <- giscoR::gisco_get_countries(
  spatialtype = "COASTL",
  epsg = "4326"
)

coast_utm <- st_transform(coast, 4087)

landCells_sf <- grid_df %>% 
  filter(is_land == 1) %>%
  st_as_sf(coords = c('LON','LAT')) %>%
  st_set_crs(4326) %>%
  st_transform(4087)

#transform from polygon shape to line
coast_utm <- st_cast(coast_utm, "MULTILINESTRING")

#calculation of the distance between the coast and our points
dist <- st_distance(coast_utm, landCells_sf)
dim(dist) # nrow = nrow of coast, ncol = nrow of land cells

# will need to compute the minimum distance for each land cell
minDist <- apply(dist, 2, function(x) min(x, na.rm=T))
minDist <- minDist/1000 # convert to km
landCells_sf$distInLand_km <- minDist
landCells <- as.data.frame(landCells_sf)

grid_df2 <- grid_df2 %>%
  left_join(landCells %>% dplyr::select(grid_df_id, distInLand_km))

# # Plot to check -- this works!
# ggplot(grid_df2)+
#   geom_point(aes(LON, LAT, col = distInLand_km))



## Make a new column to identify ocean vs inland
grid_df2 <- grid_df2 %>%
  mutate(ocean = ifelse(distInLand_km <= 200 | is_land == 0, 1, 0))

# check
grid_df2 %>%
  ggplot(aes(LON, LAT, fill=ocean))+
  geom_tile()


```

```{r plot world map of geoparsed data}

coast <- giscoR::gisco_get_countries(
  spatialtype = "COASTL",
  epsg = "4326"
)
#coast <- st_transform(coast, st_crs("ESRI:54030"))

# make a bounding box
xmn <- -180
xmx <- 180
ymn <- -90
ymx <- 90
lout <- 100

bbox_df <- data.frame(
  LON = c(
    rep(xmn, lout), 
    seq(xmn, xmx, length.out = lout),
    rep(xmx, lout),
    seq(xmx, xmn, length.out = lout)
  ),
  LAT = c(
    seq(ymn, ymx, length.out = lout),
    rep(ymx, lout),
    seq(ymx, ymn, length.out = lout),
    rep(ymn, lout)
  ),
  group = rep("bbx", lout*4)
)



## Plot NbS GEoparsing
# make a polygon from the grid tiles to plot with sf
grid_df_poly1 <- grid_df2 %>% 
  select(LON, LAT, grid_df_id, ocean) %>%
  mutate(LON = LON-(2.5/2), LAT = LAT-(2.5/2))
grid_df_poly2 <- grid_df2 %>% 
  select(LON, LAT, grid_df_id, ocean) %>%
  mutate(LON = LON-(2.5/2), LAT = LAT+(2.5/2))
grid_df_poly3 <- grid_df2 %>% 
  select(LON, LAT, grid_df_id, ocean) %>%
  mutate(LON = LON+(2.5/2), LAT = LAT+(2.5/2))
grid_df_poly4 <- grid_df2 %>% 
  select(LON, LAT, grid_df_id, ocean) %>%
  mutate(LON = LON+(2.5/2), LAT = LAT-(2.5/2))
grid_df_poly <- rbind(grid_df_poly1,grid_df_poly2,grid_df_poly3,grid_df_poly4)

grid_df_mCDR_poly <- grid_df_poly %>%
  left_join(grid_df_mCDR %>% select(grid_df_id, n_articles), by="grid_df_id") %>%
  arrange(grid_df_id)

grid_df_mCDR_poly <- grid_df_mCDR_poly %>%
  filter(ocean == 1)

#brks <- quantile(grid_df_mCDR$n_articles, probs=seq(0,1, by=0.1), na.rm=T)
#brkslabs <- formatC(brks,digits=2,format="e")
#names(brks) <- brkslabs


# Plot
geoparsedMap_ggp <- ggplot() +
  geom_polygon(data=grid_df_mCDR_poly, aes(LON, LAT, group=grid_df_id, fill=log(n_articles)))+
  scale_fill_distiller(palette = "Blues", direction = 1, name = "log(weighted articles)",
                       na.value = "transparent")+
  
  geom_sf(data=coast, col = "black", linewidth = 0.5)+
  geom_polygon(data=bbox_df, aes(x=LON, y=LAT, group=group),col = "black", linewidth = 0.7, fill=NA)+
  coord_sf(crs = st_crs('ESRI:54030'),default_crs = st_crs(4326))+
  theme_bw()+
  theme(
    legend.position = "bottom",
    panel.background = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank()
  )
  

ggsave(geoparsedMap_ggp,
       filename = here::here("figures/mCDR_research_in_france_March2024/geoparsedMap.png"),
       width = 7, height = 5, dpi = 600)
```


```{r zoom in on france}

france_coast <- giscoR::gisco_get_countries(
  resolution = "20",
  country = "France"
)

france_bbox <- st_bbox(france_coast)
france_bbox <- c(ymin = 41.2632185, ymax = 51.268318,
                 xmin = -5.4534286, xmax = 9.8678344)


			

# Plot
geoparsedMapFrance_ggp <- ggplot() +
  geom_polygon(data=grid_df_mCDR_poly, 
               aes(LON, LAT, group=grid_df_id, fill=log(n_articles)))+
  scale_fill_distiller(palette = "Blues", direction = 1, name = "log(weighted articles)",
                       na.value = "transparent")+
  
  geom_sf(data=france_coast, col = "black", linewidth = 1, fill = NA)+
  # geom_polygon(data=bbox_df, aes(x=LON, y=LAT, group=group),col = "black", linewidth = 0.7, fill=NA)+
  coord_sf(crs = st_crs('ESRI:54030'),default_crs = st_crs(4326),
           xlim = france_bbox[c("xmin","xmax")],
           ylim = france_bbox[c("ymin","ymax")])+
  theme_bw()+
  theme(
    legend.position = "none",
    panel.background = element_blank(),
    panel.grid = element_blank(),
    #panel.border = element_line(colour = "black", linewidth = 0.75),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank()
  )
  

ggsave(geoparsedMapFrance_ggp,
       filename = here::here("figures/mCDR_research_in_france_March2024/geoparsedMapFrance.png"),
       width = 7, height = 5, dpi = 600)
```

```{r try combining both maps as an inset}
library(cowplot)

mapsInset_ggp <- ggdraw() +
  draw_plot(geoparsedMap_ggp)+
  draw_plot(geoparsedMapFrance_ggp + 
              ggtitle("France metropolitan")+
              theme(title = element_text(size=9)), 
            x = -0.05, y = 0.15, width = 0.4, height = 0.4)



ggsave(mapsInset_ggp,
       filename = here::here("figures/mCDR_research_in_france_March2024/geoparsedMapInset.png"),
       width = 7, height = 5, dpi = 600)
```


```{r clean environment}
rm(coast, coast_utm, france_coast, france_bbox, bbox_df, grid_df, grid_df2, grid_df_mCDR,
   grid_df_mCDR_poly, grid_df_poly1,grid_df_poly2, grid_df_poly3, grid_df_poly4,
   landCells, landCells_sf, mCDR_df_top10_geo, weightedSum)
```

# Keyword matching -- types of mCDR 

```{r load results from keyword extract on rossi}
load(here::here("data/mCDR_data_March2024_beforeKeyword.RData"))
load(here::here("data/mCDR_data_March2024_afterKeyword.RData"))


## Get the plotting and factoring aesthetics
top10 <- with(mCDR_df_top10, table(country_aff))
top10 <- top10[order(top10, decreasing = TRUE)]
myPal <- viridis::mako(length(top10))
myPal[which(names(top10) == "France")] <- "orange"
myPal[which(names(top10) %in% c("United Kingdom","Germany","France"))] <- RColorBrewer::brewer.pal(3,"YlOrBr")
names(myPal) <- names(top10)



## For each type of option, tabulate the number of articles per country

# Merge two data frames on metadata and keyword matching
mCDR_type_tab <- mCDR_df_top10 %>%
  inner_join(matches_all, by = "analysis_id") %>%
  mutate(blue_carbon = ifelse(0.5 <= blue_carbon, TRUE, FALSE)) %>%
  select(country_aff, blue_carbon, OAE, OIF, Artificial_upwelling, 
         Deep_sea_storage, Algal_cultivation)

# Melt data into long form and tabulate
mCDR_type_tab <- reshape2::melt(mCDR_type_tab, 
                                id.vars = "country_aff", variable.name = "mCDR_method") %>%
  group_by(country_aff, mCDR_method) %>%
  summarise(n_articles = sum(value))

# Display tabulation as a proportion for each method
mCDR_type_totals <- mCDR_type_tab %>% 
  group_by(mCDR_method) %>%
  summarise(total = sum(n_articles))

mCDR_type_tab <- mCDR_type_tab %>%
  left_join(mCDR_type_totals, by = "mCDR_method") %>%
  mutate(percent_contribution = n_articles/total*100)

# Factor variable levels
mCDR_type_tab$country_aff <- factor(mCDR_type_tab$country_aff, levels= names(top10))
mCDR_type_tab$mCDR_method <- factor(mCDR_type_tab$mCDR_method,
                                    levels = c("blue_carbon", "OAE", "OIF",
                                               "Artificial_upwelling", 
                                               "Deep_sea_storage", "Algal_cultivation"),
                                    labels = c("Blue carbon","Alkalinity enhancement",
                                               "Iron fertilization",
                                               "Artificial up/down-welling", 
                                               "Deep sea storage",
                                               "Micro/macro-algal cultivation"))

```

```{r plot stacked bar plot of mCDR method}
mCDRMethodBar_ggp <- ggplot(mCDR_type_tab)+
  geom_col(position = "stack",aes(x = mCDR_method, 
                                  y = percent_contribution, 
                                  fill = country_aff))+
  geom_text(aes(x = mCDR_method, label = formatC(total, big.mark = " ")),
            y=95, size=3, col="lightgrey")+
  scale_fill_manual(values = myPal) +
  labs(x="mCDR method", y ="% contribution", fill = "Country")+
  theme_bw()+
  theme(
    axis.text.x = element_text(size=13, angle = 45, hjust=1),
    axis.text.y = element_text(size=13),
    legend.text = element_text(size=13),
    axis.title.x = element_text(size=15),
    axis.title.y = element_text(size=15),
    legend.title = element_text(size=15)
  )



ggsave(mCDRMethodBar_ggp,
       filename = here::here("figures/mCDR_research_in_france_March2024/percent_contribution_method_bar.png"),
       width = 7, height = 5, dpi = 600)
```

# Timeseries of different method types except blue carbon from keyword matching


```{r format data for CDR method timeseries plot}
load(here::here("data/mCDR_data_March2024_beforeKeyword.RData"))
load(here::here("data/mCDR_data_March2024_afterKeyword.RData"))

## For each type of option (except blue carbon), tabulate the number of articles per year

# Merge two data frames on metadata and keyword matching
mCDR_type_year_tab <- mCDR_df_top10 %>%
  filter(blue_carbon < 0.5) %>% ## EXCLUDE BLUE CARBON
  inner_join(matches_all, by = "analysis_id") %>%
  select(year, OAE, OIF, Artificial_upwelling, 
         Deep_sea_storage, Algal_cultivation)

# Melt data into long form and tabulate
mCDR_type_year_tab <- reshape2::melt(mCDR_type_year_tab, 
                                id.vars = "year", variable.name = "mCDR_method") %>%
  group_by(year, mCDR_method) %>%
  summarise(n_articles = sum(value)) 
  

# Display tabulation as a proportion for each year
year_totals <- mCDR_type_year_tab %>% 
  group_by(year) %>%
  summarise(total = sum(n_articles))

mCDR_type_year_tab <- mCDR_type_year_tab %>%
  left_join(year_totals, by = "year") %>%
  mutate(percent_contribution = n_articles/total*100)


# Factor variable levels
mCDR_type_year_tab$year_date <- as.Date(paste0(mCDR_type_year_tab$year,"-01-01"))

mCDR_type_year_tab$mCDR_method <- factor(mCDR_type_year_tab$mCDR_method,
                                    levels = c("OAE", "OIF",
                                               "Artificial_upwelling", 
                                               "Deep_sea_storage", "Algal_cultivation"),
                                    labels = c("Alkalinity enhancement",
                                               "Iron fertilization",
                                               "Artificial up/\ndown-welling", 
                                               "Deep sea storage",
                                               "Micro/macro-algal cultivation"))

# Subset years to 1995 - 2022 (b/c 2023 is incomplete)
mCDR_type_year_tab <- mCDR_type_year_tab %>%
  filter(as.Date("1995-01-01") <= year_date & year_date < as.Date("2023-01-01"))

```


```{r}
require(gcookbook)

timeseriesMethod_ggp <- ggplot(mCDR_type_year_tab,
                               aes(x = year_date, y = n_articles, fill = mCDR_method)) +
  geom_area(colour = "black", size = .2) +
  scale_fill_brewer(palette = "Dark2")+
  #scale_fill_manual(values = myPal) +
  scale_x_date()+
  labs(x="Year", y ="N articles", fill = "CDR method")+
  theme_bw()+
  theme(
    legend.position = "none",
    axis.text.x = element_text(size=13),
    axis.text.y = element_text(size=13),
    legend.text = element_text(size=13),
    axis.title.x = element_text(size=15),
    axis.title.y = element_text(size=15),
    legend.title = element_text(size=15)
  )

timeseriesMethod_ggp

timeseriesMethodPercent_ggp <- ggplot(mCDR_type_year_tab,
                               aes(x = year_date, y = percent_contribution, 
                                   fill = mCDR_method)) +
  geom_col(position = "stack") +
  scale_fill_brewer(palette = "Dark2")+
  #scale_fill_manual(values = myPal) +
  scale_x_date()+
  labs(x="Year", y ="% articles", fill = "CDR method")+
  guides(fill=guide_legend(nrow=2,byrow=TRUE))+
  theme_bw()+
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(size=13),
    axis.text.y = element_text(size=13),
    legend.text = element_text(size=13),
    axis.title.x = element_text(size=15),
    axis.title.y = element_text(size=15),
    legend.title = element_text(size=15)
  )

timeseriesMethodPercent_ggp

timeseriesMethodCombined <- egg::ggarrange(
  timeseriesMethod_ggp + theme(plot.margin = unit(c(1,2,0.5,1), "cm")), 
  timeseriesMethodPercent_ggp+ theme(plot.margin = unit(c(1,2,0.5,1), "cm")),
  nrow = 2, ncol = 1,
  heights = c(1,0.8),
  labels = c("a. Total number of articles","b. Percent contribution"))


ggsave(timeseriesMethodCombined,
  filename = here::here("figures/mCDR_research_in_france_March2024/timeseriesByMethod.png"),
       width = 8, height = 8, dpi = 600)

```


# Total number of publications ~ size of the EEZ for each country


```{r calculate eez area for each country, eval = FALSE}

# # Read the polygons of eez boundaries
# eez <- sf::st_read(here::here("data/external/eez_rast/MarineRegions_EEZ_v12_20231025"), layer="eez_v12")
# 
# # Extract country and area values
# eez_countries <- st_drop_geometry(eez)[,"SOVEREIGN1"]
# eez_area <- st_drop_geometry(eez)[,"AREA_KM2"]
# 
# rm(eez)
# 
# # Bind into data frame and save
# eez_area_df <- data.frame(
#   country_aff = eez_countries,
#   area_km2 = eez_area
# )
# 
# 
# save(eez_area_df, file = here::here("data/country_eez_area_df.RData"))

```

```{r}
load(here::here("data/mCDR_data_March2024_beforeKeyword.RData"))
load(here::here("data/country_eez_area_df.RData"))

eez_area_df <- eez_area_df %>%
  group_by(country_aff) %>%
  summarise(total_area_km2 = sum(area_km2))

mCDR_df_top10_eez <- mCDR_df_top10 %>%
  group_by(country_aff) %>%
  summarise(n_articles = n_distinct(analysis_id)) %>%
  left_join(eez_area_df, by = "country_aff")

## But try faceting by just blue carbon, and then all other techniques
mCDR_df_top10_eez_bc <- mCDR_df_top10 %>%
  filter(0.5 <= blue_carbon) %>%
  group_by(country_aff) %>%
  summarise(n_articles = n_distinct(analysis_id)) %>%
  left_join(eez_area_df, by = "country_aff") %>%
  mutate(method = "Blue carbon")

mCDR_df_top10_eez_other <- mCDR_df_top10 %>%
  filter(blue_carbon < 0.5) %>%
  group_by(country_aff) %>%
  summarise(n_articles = n_distinct(analysis_id)) %>%
  left_join(eez_area_df, by = "country_aff") %>%
  mutate(method = "Other CDR\nmethods")

mCDR_df_top10_eez_bc_facet <- rbind(mCDR_df_top10_eez_bc, mCDR_df_top10_eez_other)


pubs2eez_ggp <- ggplot()+
  ggrepel::geom_text_repel(
    data = mCDR_df_top10_eez_bc_facet %>%
      filter(country_aff != "France"), 
    aes(x = total_area_km2, y=n_articles, label = country_aff),
    box.padding = 0.05
  )+
  ggrepel::geom_text_repel(
    data = mCDR_df_top10_eez_bc_facet %>%
      filter(country_aff == "France"), 
    aes(x = total_area_km2, y=n_articles, label = country_aff), col = "red", size=5,
    box.padding = 0.05
  )+
  facet_grid(method~., scales = "free_y")+
  scale_x_continuous(expand = expansion(mult = 0.1))+
  labs(x = "EEZ area (km2)",y="N articles")+
  theme_bw()+
  theme(
    axis.text.x = element_text(size=13),
    axis.text.y = element_text(size=13),
    legend.text = element_text(size=13),
    axis.title.x = element_text(size=15),
    axis.title.y = element_text(size=15),
    legend.title = element_text(size=15),
    strip.text = element_text(size=15)
  )

pubs2eez_ggp

ggsave(pubs2eez_ggp,
       filename = here::here("figures/mCDR_research_in_france_March2024/nArticles_vs_EEZarea.png"),
       width = 7, height = 6, dpi = 600)
```




